/* NỘI DUNG GAME: khẩu hiệu, câu hỏi (kèm giải thích và căn cứ), sự kiện lừa đảo.
   Muốn sửa câu hỏi, đáp án, căn cứ: chỉ cần sửa file này. */
/* ===== KHẨU HIỆU (Kế hoạch hưởng ứng Ngày Chuyển đổi số quốc gia của phường) ===== */
const SLOGANS=[
 "Nhiệt liệt chào mừng Ngày Chuyển đổi số quốc gia – ngày 10 tháng 10",
 "Chuyển đổi số thiết thực vì người dân, doanh nghiệp và sự phát triển của Thành phố",
 "Chuyển đổi số thiết thực, an toàn, hiệu quả",
 "Mỗi người dân một kỹ năng số; mỗi gia đình thêm một tiện ích số",
 "Sử dụng dịch vụ số an toàn, bảo vệ dữ liệu cá nhân, nâng cao niềm tin số",
 "Mỗi doanh nghiệp một giải pháp số, mỗi giải pháp tạo thêm giá trị",
 "Khai thác dữ liệu hiệu quả, nâng cao chất lượng quản lý và phục vụ",
 "Khai thông nguồn lực số, thúc đẩy chuyển đổi xanh, hướng tới phát triển bền vững",
 "Thành phố Hồ Chí Minh tiên phong chuyển đổi số, phát huy đổi mới sáng tạo, bứt phá phát triển"
];
const ITEMS=["Băng rôn tuyên truyền","Áp phích Ngày 10/10","Cờ phướn chuyển đổi số","Tờ rơi Công dân số","Standee Ngày hội"];

/* ===== NGÂN HÀNG CÂU HỎI (giải thích + nội dung căn cứ) ===== */
const QZ=(q,a,w,ex,law)=>({q,a,w,ex,law});
const BANK1=[
 QZ("Mật khẩu nào an toàn nhất?","Dài, có chữ hoa, chữ thường, số và ký hiệu",["Ngày sinh của mình","123456"],"Mật khẩu ngắn, dễ đoán như ngày sinh hay 123456 bị kẻ gian dò ra chỉ trong vài giây.","Khuyến cáo an toàn thông tin: mật khẩu nên dài từ 8 ký tự trở lên, kết hợp chữ hoa, chữ thường, số, ký hiệu và không dùng chung cho nhiều tài khoản."),
 QZ("Người xưng nhân viên ngân hàng xin mã OTP. Con làm gì?","Không đưa mã OTP cho bất kỳ ai",["Đưa vì họ là nhân viên ngân hàng","Đưa nếu họ hứa giúp"],"OTP là \"chìa khóa\" để xác nhận giao dịch. Ai có OTP là có thể rút tiền trong tài khoản của mình.","Các ngân hàng đều thông báo: ngân hàng không bao giờ yêu cầu khách hàng cung cấp mật khẩu, mã OTP qua điện thoại, tin nhắn hay mạng xã hội."),
 QZ("Dùng Wi-Fi miễn phí ở quán cà phê, nên tránh việc gì?","Đăng nhập ngân hàng, chuyển tiền",["Đọc báo","Xem bản đồ"],"Wi-Fi công cộng không có mật khẩu hoặc dùng chung mật khẩu có thể bị kẻ gian nghe lén dữ liệu.","Khuyến cáo an toàn thông tin: chỉ giao dịch ngân hàng bằng mạng di động (3G/4G/5G) hoặc Wi-Fi tin cậy ở nhà."),
 QZ("Thấy tin \"cúp điện cả phường 3 ngày\" không rõ nguồn trên mạng xã hội. Làm gì?","Kiểm tra trên trang chính thức, không chia sẻ",["Chia sẻ ngay cho mọi người","Bình luận thêm cho sôi nổi"],"Chia sẻ tin chưa kiểm chứng là góp phần lan truyền tin giả, có thể bị xử lý.","Luật An ninh mạng 2025 (Điều 7, khoản 1, điểm c và d) nghiêm cấm đăng tải, phát tán thông tin bịa đặt, sai sự thật gây hoang mang trong Nhân dân."),
 QZ("Tài khoản mạng xã hội ở Việt Nam phải xác thực bằng gì?","Số điện thoại di động tại Việt Nam (không có thì dùng số định danh cá nhân)",["Email bất kỳ","Không cần xác thực"],"Xác thực giúp biết ai đứng sau tài khoản, hạn chế tài khoản ảo lừa đảo, tung tin giả.","Nghị định 147/2024/NĐ-CP (hiệu lực 25/12/2024) quy định: tài khoản mạng xã hội phải được xác thực bằng số điện thoại di động tại Việt Nam; chỉ khi người dùng không có số điện thoại mới xác thực bằng số định danh cá nhân."),
 QZ("Đăng ảnh con cháu kèm tên trường, địa chỉ nhà ở chế độ công khai có nên không?","Không nên, kẻ xấu có thể lợi dụng",["Càng chi tiết càng tốt","Không sao cả"],"Kẻ xấu có thể dùng thông tin để giả làm người quen đón trẻ, lừa phụ huynh chuyển tiền \"cấp cứu\".","Luật Trẻ em 2016 quy định trẻ em có quyền được bảo vệ bí mật đời sống riêng tư; Luật Bảo vệ dữ liệu cá nhân 2025 bảo vệ dữ liệu cá nhân của mỗi người."),
 QZ("Quét mã QR trả tiền ở quán, cần xem gì trước khi bấm xác nhận?","Tên người nhận hiện trên ứng dụng ngân hàng",["Màu của mã QR","Không cần xem gì"],"Kẻ gian có thể dán đè mã QR giả lên mã thật của quán. Nhìn tên người nhận là biết tiền có tới đúng chủ quán không.","Khuyến cáo của Công an và các ngân hàng: kiểm tra kỹ tên chủ tài khoản nhận tiền trước khi xác nhận chuyển khoản."),
 QZ("Tin nhắn: \"Tài khoản ngân hàng của bạn bị khóa, bấm link để mở\". Làm gì?","Không bấm, gọi tổng đài in trên thẻ ngân hàng",["Bấm link để mở khóa","Nhắn lại mã OTP"],"Link trong tin nhắn dẫn tới trang giả, đánh cắp tài khoản ngân hàng.","Các ngân hàng thông báo: ngân hàng không gửi đường link yêu cầu khách hàng đăng nhập hay cập nhật thông tin qua tin nhắn."),
 QZ("Thanh toán không dùng tiền mặt có lợi gì?","Nhanh, có lịch sử giao dịch, tránh tiền giả",["Không cần giữ bí mật mật khẩu","Chuyển nhầm thì tự hoàn tiền"],"Mỗi giao dịch đều được lưu lại nên dễ đối chiếu, không lo thối nhầm hay nhận tiền giả.","Quyết định 1813/QĐ-TTg ngày 28/10/2021 của Thủ tướng phê duyệt Đề án phát triển thanh toán không dùng tiền mặt, khuyến khích người dân thanh toán điện tử."),
 QZ("Shipper giao món hàng mình không đặt, đòi thu tiền. Làm gì?","Kiểm tra đơn trên ứng dụng; không đặt thì từ chối",["Trả tiền cho nhanh","Nhận giùm rồi trả tiền"],"Kẻ gian gửi hàng kém chất lượng đến nhiều nhà, ai trả tiền là mất tiền.","Người tiêu dùng có quyền từ chối nhận hàng mình không đặt mua."),
 QZ("Người chơi dưới 18 tuổi được chơi game online tối đa bao lâu mỗi ngày?","Không quá 60 phút mỗi trò, tổng không quá 180 phút mỗi ngày",["Không giới hạn","5 tiếng mỗi trò"],"Giới hạn giờ chơi giúp các em không bị nghiện game.","Điều 39 Nghị định 147/2024/NĐ-CP: doanh nghiệp game phải có hệ thống bảo đảm người chơi dưới 18 tuổi chơi không quá 60 phút mỗi trò chơi và không quá 180 phút mỗi ngày."),
 QZ("Có người gửi link nhờ \"cài VNeID bản mới\" để nhận hỗ trợ. Làm gì?","Không bấm link; chỉ cài, cập nhật VNeID từ CH Play hoặc App Store",["Cài theo link cho nhanh","Gửi mật khẩu để họ cài giùm"],"Ứng dụng giả qua link lạ có thể chiếm quyền điều khiển điện thoại, rút sạch tiền.","Nghị định 356/2025/NĐ-CP (Điều 4) xếp tên đăng nhập, mật khẩu tài khoản định danh điện tử vào danh mục dữ liệu cá nhân nhạy cảm, cần được bảo vệ đặc biệt."),
 QZ("Chụp ảnh thẻ căn cước đăng lên mạng xã hội có an toàn không?","Không, ảnh thẻ căn cước là dữ liệu cá nhân nhạy cảm",["An toàn nếu che một góc","Chỉ cần để chế độ bạn bè"],"Kẻ gian có thể dùng ảnh căn cước để mở tài khoản, vay tiền đứng tên mình.","Nghị định 356/2025/NĐ-CP (Điều 4) quy định hình ảnh thẻ căn cước, căn cước công dân, chứng minh nhân dân thuộc danh mục dữ liệu cá nhân nhạy cảm."),
 QZ("Đăng ký tuyển sinh lớp 1, lớp 6 ở TP.HCM làm thế nào?","Trực tuyến trên cổng tuyển sinh đầu cấp của Sở Giáo dục và Đào tạo",["Nhờ người quen \"lo chỗ\"","Nộp tiền cho trang lạ"],"Đăng ký trực tuyến minh bạch, không cần nhờ ai \"lo chỗ\".","Sở Giáo dục và Đào tạo TP.HCM tổ chức tuyển sinh lớp 1, lớp 6 trực tuyến tại cổng tuyensinhdaucap.hcm.edu.vn."),
 QZ("Trang web cơ quan nhà nước thường có đuôi tên miền gì?",".gov.vn",[".xyz",".top"],"Coi chừng trang giả cố tình chèn chữ \"gov.vn\" vào giữa, kiểu \"dichvucong-gov.vn.com\".","Tên miền .gov.vn dành riêng cho cơ quan nhà nước Việt Nam."),
 QZ("Điện thoại báo có bản cập nhật phần mềm. Nên làm gì?","Cập nhật để vá lỗi bảo mật",["Không bao giờ cập nhật","Chờ máy hư mới cập nhật"],"Bản cập nhật vá những lỗ hổng mà kẻ gian có thể lợi dụng.","Khuyến cáo an toàn thông tin: luôn cập nhật hệ điều hành và ứng dụng từ nguồn chính thức."),
 QZ("Muốn phản ánh, kiến nghị với chính quyền Thành phố (đường hư, ngập nước, tiếng ồn…) thì gọi tổng đài nào?","Tổng đài 1022 của TP.HCM",["Gọi 1080","Không cần báo, chờ người khác báo"],"Gọi 1022 miễn phí cước; cũng có thể nhắn Zalo 1022 hoặc phản ánh trên ứng dụng Công dân số TP.HCM, phản ánh được chuyển đúng nơi xử lý.","Hệ thống 1022 của TP.HCM là kênh chính thức tiếp nhận, chuyển xử lý và trả lời phản ánh, kiến nghị của người dân qua tổng đài 1022 (miễn phí cước gọi), Zalo, ứng dụng Công dân số TP.HCM."),
 QZ("Lỡ chuyển tiền cho kẻ lừa đảo. Việc đầu tiên nên làm?","Báo ngay ngân hàng và trình báo Công an phường",["Im lặng cho qua","Thuê \"dịch vụ lấy lại tiền\" trên mạng"],"Báo càng sớm càng có cơ hội phong tỏa tài khoản nhận tiền.","Công an cảnh báo: các \"dịch vụ lấy lại tiền bị lừa\" trên mạng thường là lừa đảo lần hai."),
 QZ("Thông tin nào là dữ liệu cá nhân?","Họ tên, số điện thoại, ảnh chân dung, số căn cước",["Chỉ số tài khoản ngân hàng","Không có gì cần giữ"],"Bất cứ thông tin nào giúp nhận ra một người đều là dữ liệu cá nhân.","Luật Bảo vệ dữ liệu cá nhân (Luật số 91/2025/QH15, hiệu lực 1/1/2026): dữ liệu cá nhân là thông tin gắn với một người cụ thể hoặc giúp xác định một người cụ thể."),
 QZ("Đèn đường trước hẻm bị hư, phản ánh nhanh qua đâu?","Ứng dụng Công dân số TP.HCM",["Đăng lên nhóm chợ","Chờ ai đó báo"],"Phản ánh qua ứng dụng được chuyển đúng nơi xử lý, mình theo dõi được kết quả.","Ứng dụng Công dân số TP.HCM có mục phản ánh hiện trường, kết nối người dân với chính quyền Thành phố.")
];
/* đố vui về Ngày 10/10 */
const DOVUI=[
 QZ("Ngày Chuyển đổi số quốc gia là ngày nào?","Ngày 10 tháng 10 hằng năm",["Ngày 1 tháng 1","Ngày 2 tháng 9"],"Ngày này nhắc mọi người cùng tham gia chuyển đổi số.","Quyết định 505/QĐ-TTg ngày 22/4/2022 của Thủ tướng Chính phủ lấy ngày 10 tháng 10 hằng năm là Ngày Chuyển đổi số quốc gia."),
QZ("Khẩu hiệu nào có trong Kế hoạch hưởng ứng Ngày Chuyển đổi số quốc gia của phường?","Mỗi người dân một kỹ năng số; mỗi gia đình thêm một tiện ích số",["Số hóa là xong việc","Ai rành công nghệ thì mới cần"],"Ai cũng nên có ít nhất một kỹ năng số, mỗi nhà dùng thêm một tiện ích số như VNeID, thanh toán bằng mã QR.","Kế hoạch hưởng ứng Ngày Chuyển đổi số quốc gia 10/10/2026 của UBND phường Gia Định đưa khẩu hiệu này vào danh sách khẩu hiệu tuyên truyền."),
 QZ("Ba trụ cột của chuyển đổi số quốc gia là gì?","Chính phủ số, kinh tế số, xã hội số",["Internet, điện thoại, máy tính","Ngân hàng, chợ, trường học"],"Ba trụ cột: chính quyền phục vụ trên môi trường số, doanh nghiệp làm ăn trên môi trường số, người dân sống trên môi trường số.","Quyết định 749/QĐ-TTg ngày 3/6/2020 phê duyệt Chương trình Chuyển đổi số quốc gia với 3 trụ cột: chính phủ số, kinh tế số, xã hội số."),
];
/* ===== MÀN 2: CÂU HỎI CHUNG Ở TRUNG TÂM ===== */
const BANK2=[
 QZ("Tài khoản định danh điện tử mức 2 khác mức 1 ở điểm nào?","Được Công an xác thực trực tiếp, dùng được nhiều dịch vụ hơn",["Không khác gì","Mức 2 phải trả phí hằng tháng"],"Mức 2 dùng được hầu hết dịch vụ công trực tuyến và thay giấy tờ khi làm thủ tục.","Nghị định 69/2024/NĐ-CP: tài khoản mức 1 do người dân tự đăng ký trên ứng dụng VNeID; tài khoản mức 2 được cấp sau khi cơ quan Công an thu nhận, xác thực ảnh chân dung và vân tay."),
 QZ("Cần chuẩn bị gì để được cấp tài khoản định danh điện tử mức 2?","Thẻ căn cước và số điện thoại đứng tên chính mình",["Sổ hộ khẩu và ảnh 3x4","Nộp phí qua điện thoại"],"Việc cấp tài khoản định danh điện tử không mất phí.","Nghị định 69/2024/NĐ-CP: công dân mang thẻ căn cước, dùng số điện thoại chính chủ, được thu nhận ảnh chân dung và vân tay tại cơ quan Công an."),
 QZ("Căn cước điện tử trên VNeID có giá trị gì?","Chứng minh căn cước khi làm thủ tục, giao dịch",["Chỉ để xem","Phải kèm bản photo công chứng"],"Đi làm thủ tục chỉ cần mở VNeID, không cần mang bản photo.","Điều 33 Luật Căn cước 2023: căn cước điện tử có giá trị chứng minh về căn cước và các thông tin đã tích hợp khi thực hiện thủ tục hành chính, dịch vụ công và các giao dịch khác."),
 QZ("Người quen mượn tài khoản VNeID \"làm hồ sơ giùm\". Bạn làm sao?","Không cho mượn, không đưa mật khẩu hay OTP",["Cho mượn vì là người quen","Đưa OTP, giữ mật khẩu"],"Tài khoản gắn với chính bạn; người khác dùng có thể làm việc xấu đứng tên bạn.","Nghị định 356/2025/NĐ-CP xếp tên đăng nhập, mật khẩu tài khoản định danh điện tử vào dữ liệu cá nhân nhạy cảm."),
 QZ("Làm thủ tục còn phải nộp sổ hộ khẩu giấy không?","Không, sổ hộ khẩu đã hết giá trị từ 1/1/2023",["Vẫn phải nộp bản gốc","Phải nộp bản công chứng"],"Thông tin cư trú nay nằm trong Cơ sở dữ liệu về cư trú.","Khoản 3 Điều 38 Luật Cư trú 2020: sổ hộ khẩu, sổ tạm trú đã cấp chỉ được sử dụng đến hết ngày 31/12/2022."),
 QZ("Thông tin đã có trong Cơ sở dữ liệu quốc gia về dân cư, cán bộ có được bắt nộp lại giấy tờ chứng minh không?","Không, cán bộ khai thác từ cơ sở dữ liệu",["Có, phải nộp đủ","Tùy cán bộ"],"Dữ liệu dùng chung giúp người dân đỡ phải mang nhiều giấy tờ.","Nghị định 104/2022/NĐ-CP bỏ yêu cầu xuất trình sổ hộ khẩu, sổ tạm trú; cơ quan giải quyết khai thác thông tin cư trú qua cơ sở dữ liệu, thẻ căn cước hoặc ứng dụng VNeID."),
 QZ("Bước đầu tiên để nộp hồ sơ trên Cổng Dịch vụ công là gì?","Đăng nhập bằng tài khoản VNeID",["In hồ sơ ra giấy","Gọi cán bộ đọc thông tin"],"Sau khi đăng nhập: chọn thủ tục, điền tờ khai, đính kèm giấy tờ rồi nộp.","Cổng Dịch vụ công quốc gia dùng tài khoản định danh điện tử (VNeID) để đăng nhập một lần cho tất cả dịch vụ."),
 QZ("Nộp hồ sơ xong, cần lưu gì để tra cứu tiến độ?","Mã hồ sơ",["Ảnh chụp trang chủ","Số điện thoại cán bộ"],"Có mã hồ sơ là tra cứu được trên Cổng Dịch vụ công hoặc ứng dụng Công dân số TP.HCM.","Mỗi hồ sơ được cấp một mã số riêng để theo dõi quá trình giải quyết."),
 QZ("Văn bản ký bằng chữ ký số hợp lệ có giá trị thế nào?","Có giá trị pháp lý như chữ ký tay",["Phải in ra ký tay lại","Chỉ dùng trong nội bộ"],"Chữ ký số còn giúp phát hiện văn bản bị sửa sau khi ký.","Luật Giao dịch điện tử 2023 (hiệu lực 1/7/2024): chữ ký số bảo đảm an toàn có giá trị pháp lý tương đương chữ ký của người đó trên văn bản giấy."),
 QZ("Kết quả giải quyết thủ tục bản điện tử có giá trị thế nào?","Giá trị pháp lý như bản giấy",["Chỉ để tham khảo","Phải in ra đóng dấu lại"],"Bản điện tử được lưu trong kho dữ liệu của mình, dùng lại được nhiều lần.","Nghị định 45/2020/NĐ-CP: kết quả giải quyết thủ tục hành chính bản điện tử có giá trị pháp lý như kết quả bằng giấy."),
 QZ("Có xin được bản sao điện tử chứng thực từ bản chính không?","Có, tại cơ quan có thẩm quyền, dùng khi nộp hồ sơ trực tuyến",["Không, chỉ có bản giấy","Tự chụp điện thoại là được"],"Ảnh tự chụp không có giá trị như bản sao chứng thực.","Nghị định 45/2020/NĐ-CP (sửa đổi Nghị định 23/2015/NĐ-CP): bản sao điện tử chứng thực từ bản chính có giá trị sử dụng thay cho bản chính trong giao dịch điện tử."),
 QZ("Bộ phận Một cửa ở Trung tâm làm nhiệm vụ gì?","Hướng dẫn, tiếp nhận hồ sơ và trả kết quả thủ tục",["Chỉ phát số thứ tự","Chỉ thu tiền lệ phí"],"Người dân chỉ cần đến một nơi, không phải chạy nhiều phòng.","Nghị định 61/2018/NĐ-CP về cơ chế một cửa: Bộ phận Một cửa hướng dẫn, tiếp nhận, chuyển hồ sơ và trả kết quả giải quyết thủ tục hành chính."),
 QZ("Gia đình có người mất, liên thông thủ tục giải quyết cùng lúc những gì?","Đăng ký khai tử, xóa đăng ký thường trú, hưởng mai táng phí/tử tuất",["Chỉ khai tử","Phải đi 3 nơi riêng"],"Gia đình chỉ cần nộp một bộ hồ sơ.","Nghị định 63/2024/NĐ-CP quy định liên thông điện tử nhóm thủ tục: đăng ký khai tử – xóa đăng ký thường trú – hưởng chế độ tử tuất, mai táng phí."),
 QZ("Nộp lệ phí thủ tục trực tuyến bằng cách nào?","Thanh toán trực tuyến ngay trên Cổng Dịch vụ công",["Chuyển khoản cá nhân cho người lạ","Đưa tiền cho người \"làm nhanh\""],"Thanh toán trên Cổng có biên lai điện tử, không lo bị lừa.","Cổng Dịch vụ công quốc gia có chức năng thanh toán trực tuyến phí, lệ phí và cấp biên lai điện tử."),
 QZ("Trước cổng có người mời \"làm hồ sơ nhanh, có phí\". Bạn làm gì?","Từ chối; nộp tại quầy hoặc trực tuyến, cần thì hỏi cán bộ",["Đồng ý cho nhanh","Đưa luôn căn cước cho họ"],"\"Cò\" hồ sơ có thể làm lộ thông tin cá nhân và mất tiền oan.","Mọi thủ tục được công khai quy trình, thời hạn, lệ phí tại Bộ phận Một cửa; người dân không cần qua trung gian."),
 QZ("Nộp hồ sơ trực tuyến có bắt buộc đến nhận kết quả không?","Không, có thể nhận qua bưu chính công ích hoặc bản điện tử",["Bắt buộc phải đến","Phải đến 2 lần"],"Ở nhà vẫn nhận được kết quả.","Quyết định 45/2016/QĐ-TTg: người dân có thể đăng ký nhận kết quả giải quyết thủ tục hành chính qua dịch vụ bưu chính công ích."),
 QZ("Sau khi làm xong thủ tục, người dân có thể làm gì ngay tại quầy?","Đánh giá mức độ hài lòng trên máy tính bảng hoặc Cổng Dịch vụ công",["Không được đánh giá","Phải viết đơn gửi giấy"],"Ý kiến của người dân giúp Trung tâm phục vụ tốt hơn.","Nghị định 61/2018/NĐ-CP (sửa đổi bởi Nghị định 107/2021/NĐ-CP): tổ chức, cá nhân được đánh giá việc giải quyết thủ tục hành chính."),
 QZ("Người lớn tuổi chưa rành nộp hồ sơ online thì nhờ ai?","Đoàn viên, Tổ công nghệ số cộng đồng hướng dẫn miễn phí",["Người lạ trên Facebook","Dịch vụ thu phí ngoài cổng"],"Ở Trung tâm và khu phố đều có người hỗ trợ miễn phí.","Tổ công nghệ số cộng đồng ở các khu phố có nhiệm vụ hướng dẫn người dân sử dụng nền tảng số, dịch vụ công trực tuyến."),
 QZ("Giấy phép lái xe đã tích hợp vào VNeID có dùng được khi bị kiểm tra không?","Được, xuất trình trên VNeID thay bản giấy",["Không, phải mang bản giấy","Chỉ dùng ảnh chụp"],"Ảnh chụp giấy phép lái xe thì không có giá trị.","Từ ngày 1/7/2024, giấy phép lái xe đã tích hợp trên VNeID được xuất trình thay bản giấy (Luật Căn cước 2023)."),
 QZ("Muốn xin Phiếu lý lịch tư pháp, có thể làm trực tuyến ở đâu?","Trên VNeID hoặc Cổng Dịch vụ công quốc gia",["Qua trang lạ thu phí","Không thể làm online"],"Không cần xếp hàng, kết quả có thể nhận bản điện tử.","Điều 22 Nghị định 216/2026/NĐ-CP: cá nhân yêu cầu cấp Phiếu lý lịch tư pháp trực tuyến thì khai tờ khai điện tử trên ứng dụng VNeID hoặc Cổng Dịch vụ công quốc gia."),
 QZ("Lỡ để lộ mật khẩu VNeID. Bạn làm gì?","Đổi mật khẩu ngay, cần thì khóa tài khoản và báo Công an",["Để đó","Đăng lên mạng hỏi"],"Xử lý càng sớm càng tránh bị kẻ gian dùng tài khoản.","Nghị định 356/2025/NĐ-CP: mật khẩu tài khoản định danh điện tử là dữ liệu cá nhân nhạy cảm."),
 QZ("Quên mật khẩu VNeID thì làm sao?","Dùng chức năng \"Quên mật khẩu\" trên ứng dụng chính thức",["Nhờ người lạ \"mở khóa có phí\"","Tạo tài khoản mới"],"Dịch vụ \"mở khóa VNeID\" trên mạng là lừa đảo.","Ứng dụng VNeID có chức năng lấy lại mật khẩu bằng số điện thoại đã đăng ký."),
 QZ("Hồ sơ nộp còn thiếu giấy tờ, cán bộ phải làm gì?","Hướng dẫn người dân bổ sung, hoàn thiện hồ sơ",["Trả hồ sơ, không nói lý do","Bắt nộp lại từ đầu nhiều lần"],"Người dân được hướng dẫn rõ ràng, không phải đi lại nhiều lần.","Nghị định 61/2018/NĐ-CP: hồ sơ chưa đầy đủ thì cán bộ hướng dẫn người nộp bổ sung, hoàn thiện một lần, đầy đủ."),
 QZ("Bị yêu cầu nộp thêm giấy tờ ngoài quy định, bạn có quyền gì?","Phản ánh, kiến nghị qua Cổng Dịch vụ công hoặc đường dây nóng",["Không có quyền gì","Phải làm theo"],"Thành phần hồ sơ đã được công khai, không được đòi thêm.","Nghị định 20/2008/NĐ-CP: người dân có quyền phản ánh, kiến nghị về quy định hành chính và hành vi của cán bộ khi giải quyết thủ tục."),
 QZ("Hồ sơ giấy nộp tại quầy được số hóa để làm gì?","Lần sau tái sử dụng, không phải nộp lại",["Để bán dữ liệu","Không để làm gì"],"Giấy tờ đã số hóa được lưu trong kho dữ liệu của người dân.","Nghị định 45/2020/NĐ-CP và Nghị định 107/2021/NĐ-CP: hồ sơ, kết quả thủ tục được số hóa, lưu giữ để tái sử dụng.")
];
/* ===== MÀN 2: CÂU HỎI THEO THỦ TỤC ===== */
const PROC={
 A:{name:"Đăng ký khai sinh",quay:1,place:"Quầy 1",qs:[
  QZ("Cha mẹ phải đăng ký khai sinh cho con trong thời hạn bao lâu?","60 ngày kể từ ngày sinh",["1 năm","Khi nào con đi học"],"Khai sinh đúng hạn để bé có ngay số định danh cá nhân, thẻ bảo hiểm y tế.","Khoản 1 Điều 15 Luật Hộ tịch 2014: trong thời hạn 60 ngày kể từ ngày sinh con, cha hoặc mẹ có trách nhiệm đăng ký khai sinh cho con."),
  QZ("Đi đăng ký khai sinh cần nộp gì?","Tờ khai theo mẫu và giấy chứng sinh",["Sổ hộ khẩu","Ảnh 3x4 của bé"],"Giấy chứng sinh do bệnh viện, cơ sở y tế cấp khi bé chào đời.","Khoản 1 Điều 16 Luật Hộ tịch 2014: người đi đăng ký khai sinh nộp tờ khai theo mẫu và giấy chứng sinh cho cơ quan đăng ký hộ tịch."),
  QZ("Cha mẹ không thể đi đăng ký khai sinh thì ai được làm thay?","Ông, bà, người thân thích khác hoặc người đang nuôi dưỡng trẻ",["Không ai được làm thay","Bất kỳ người lạ nào"],"Quan trọng là bé được khai sinh đúng hạn.","Khoản 1 Điều 15 Luật Hộ tịch 2014: trường hợp cha, mẹ không thể đăng ký khai sinh thì ông hoặc bà, người thân thích khác, cá nhân, tổ chức đang nuôi dưỡng trẻ có trách nhiệm đăng ký."),
  QZ("Khai sinh cho bé dưới 6 tuổi theo liên thông được giải quyết cùng lúc những gì?","Khai sinh, đăng ký thường trú, cấp thẻ bảo hiểm y tế",["Chỉ khai sinh","Khai sinh và làm hộ chiếu"],"Nộp một lần, nhận đủ 3 kết quả.","Nghị định 63/2024/NĐ-CP (từ 1/7/2024): liên thông điện tử nhóm thủ tục đăng ký khai sinh – đăng ký thường trú – cấp thẻ bảo hiểm y tế cho trẻ dưới 6 tuổi.")]},
 B:{name:"Chứng thực bản sao",quay:2,place:"Quầy 2 (Sao y – Chứng thực)",qs:[
  QZ("Bản sao được chứng thực từ bản chính có giá trị thế nào?","Dùng thay cho bản chính đã đối chiếu trong giao dịch",["Chỉ dùng trong 3 tháng","Không có giá trị"],"Không phải mang bản gốc đi khắp nơi.","Khoản 2 Điều 3 Nghị định 23/2015/NĐ-CP: bản sao được chứng thực từ bản chính có giá trị sử dụng thay cho bản chính đã dùng để đối chiếu chứng thực trong các giao dịch."),
  QZ("Giấy tờ bản chính bị tẩy xóa, sửa chữa có được chứng thực bản sao không?","Không",["Được nếu nộp thêm phí","Được nếu chỉ sửa ít"],"Giữ giấy tờ gốc cẩn thận, không tự sửa chữa.","Điều 22 Nghị định 23/2015/NĐ-CP: bản chính bị tẩy xóa, sửa chữa, thêm, bớt nội dung không hợp lệ thì không được dùng làm cơ sở chứng thực bản sao."),
  QZ("Chứng thực chữ ký thì người yêu cầu phải làm gì?","Ký trước mặt người thực hiện chứng thực",["Ký sẵn ở nhà mang đến","Nhờ người khác ký giùm"],"Để xác nhận đúng là chữ ký của chính mình.","Điều 24 Nghị định 23/2015/NĐ-CP: người thực hiện chứng thực yêu cầu người yêu cầu chứng thực ký trước mặt."),
  QZ("Muốn có bản sao điện tử để nộp hồ sơ online thì làm sao?","Yêu cầu chứng thực bản sao điện tử từ bản chính",["Tự chụp điện thoại là được","Không có cách nào"],"Bản sao điện tử chứng thực dùng được nhiều lần khi nộp hồ sơ trực tuyến.","Nghị định 45/2020/NĐ-CP: bản sao điện tử chứng thực từ bản chính có giá trị sử dụng thay cho bản chính trong giao dịch điện tử.")]},
 C:{name:"Đăng ký thường trú",quay:0,place:"Công an phường",qs:[
  QZ("Muốn đăng ký thường trú thì nộp hồ sơ ở đâu?","Công an phường nơi mình cư trú (hoặc nộp trực tuyến)",["Tổ dân phố","Trường học gần nhà"],"Đăng ký cư trú là việc của Công an phường, không làm ở Trung tâm Phục vụ hành chính công.","Luật Cư trú 2020 (khoản 4 Điều 2, khoản 1 Điều 22): cơ quan đăng ký cư trú là Công an cấp xã; người đăng ký thường trú nộp hồ sơ đến cơ quan đăng ký cư trú nơi mình cư trú."),
  QZ("Khi nộp hồ sơ đăng ký thường trú, cơ quan đăng ký cư trú giao cho bạn gì?","Phiếu tiếp nhận hồ sơ; thiếu thì được hướng dẫn bổ sung",["Sổ hộ khẩu mới ngay tại chỗ","Không giao gì cả"],"Giữ phiếu tiếp nhận để theo dõi hồ sơ.","Khoản 2 Điều 22 Luật Cư trú 2020: cơ quan đăng ký cư trú kiểm tra, cấp phiếu tiếp nhận hồ sơ; hồ sơ chưa đầy đủ thì hướng dẫn bổ sung."),
  QZ("Chuyển đến chỗ ở hợp pháp mới và đủ điều kiện, phải đăng ký thường trú trong bao lâu?","12 tháng kể từ ngày đủ điều kiện",["Không cần đăng ký","5 năm"],"Đăng ký đúng hạn để thông tin cư trú luôn chính xác.","Khoản 4 Điều 22 Luật Cư trú 2020: người đã đăng ký thường trú chuyển đến chỗ ở hợp pháp khác và đủ điều kiện thì phải đăng ký thường trú tại nơi ở mới trong thời hạn 12 tháng."),
  QZ("Sau khi đăng ký thường trú, bạn có nhận sổ hộ khẩu không?","Không, thông tin được cập nhật vào Cơ sở dữ liệu về cư trú",["Có, nhận sổ mới","Nhận sổ tạm trú"],"Thông tin cư trú xem được trên ứng dụng VNeID.","Luật Cư trú 2020 (khoản 3 Điều 22, khoản 3 Điều 38): thông tin thường trú được cập nhật vào Cơ sở dữ liệu về cư trú; sổ hộ khẩu chỉ dùng đến hết 31/12/2022.")]}
};

/* ===== MÀN 3: NGÀY HỘI CHUYỂN ĐỔI SỐ (mỗi gian 1 câu, sân khấu 1 câu) ===== */
const BANK3={
 g1:[
  QZ("Luật Chuyển đổi số có hiệu lực từ khi nào?","Ngày 1/7/2026",["Ngày 10/10/2022","Chưa có luật này"],"Đây là luật đầu tiên quy định toàn diện về chuyển đổi số ở Việt Nam.","Khoản 1 Điều 47 Luật Chuyển đổi số (Luật số 148/2025/QH15): Luật có hiệu lực thi hành từ ngày 01/7/2026."),
  QZ("Theo Luật Chuyển đổi số, người dân được bảo đảm quyền gì?","Được phổ cập năng lực số cơ bản",["Không có quyền gì","Chỉ doanh nghiệp được hỗ trợ"],"Ai cũng được học để dùng được dịch vụ số.","Khoản 4 Điều 41 Luật Chuyển đổi số 2025: công dân được phổ cập năng lực số cơ bản.")],
 g2:[
  QZ("Video người thân gọi đến xin chuyển tiền gấp, hình hơi giật, môi lệch tiếng. Đây có thể là gì?","Video giả mạo bằng trí tuệ nhân tạo (deepfake)",["Do mạng chậm, cứ chuyển tiền","Chắc chắn là người thật"],"Trí tuệ nhân tạo làm giả được cả gương mặt lẫn giọng nói. Luôn gọi lại vào số quen của người thân để xác minh trước khi chuyển tiền.","Bộ Công an nhiều lần cảnh báo thủ đoạn dùng công nghệ deepfake giả hình ảnh, giọng nói người thân trong cuộc gọi video để lừa chuyển tiền; người dân cần xác minh bằng cách gọi lại số quen."),
  QZ("Trò chuyện với trợ lý ảo (AI), có nên gửi ảnh thẻ căn cước, mật khẩu VNeID để nhờ làm giùm thủ tục không?","Không, đó là dữ liệu cá nhân nhạy cảm, không đưa vào trợ lý ảo",["Được, trợ lý ảo giữ bí mật","Chỉ gửi mật khẩu là được"],"Hỏi trợ lý ảo cách làm thì được, nhưng tuyệt đối không gửi giấy tờ, mật khẩu, mã OTP.","Điều 4 Nghị định 356/2025/NĐ-CP xếp hình ảnh thẻ căn cước và tên đăng nhập, mật khẩu tài khoản định danh điện tử vào danh mục dữ liệu cá nhân nhạy cảm, cần được bảo vệ đặc biệt.")],
 g3:[
  QZ("Trẻ em dưới 16 tuổi muốn có tài khoản mạng xã hội thì sao?","Cha, mẹ hoặc người giám hộ đăng ký bằng thông tin của mình và giám sát",["Mượn số điện thoại người lạ để đăng ký","Khai tăng tuổi cho đủ"],"Trẻ em cần người lớn đồng hành để an toàn trên mạng.","Nghị định 147/2024/NĐ-CP quy định: người sử dụng mạng xã hội là trẻ em dưới 16 tuổi thì cha, mẹ hoặc người giám hộ đăng ký tài khoản bằng thông tin của mình và chịu trách nhiệm giám sát."),
  QZ("Muốn học kỹ năng số miễn phí tại nhà, vào đâu?","Nền tảng \"Bình dân học vụ số\"",["Khóa học qua link lạ thu phí trước","Không có nơi miễn phí"],"Nền tảng có bài học ngắn về dùng điện thoại, dịch vụ công, an toàn trên mạng.","Bình dân học vụ số là nền tảng học trực tuyến mở, miễn phí, giúp mọi người dân phổ cập kỹ năng số."),
  QZ("Con học trực tuyến, phụ huynh nên làm gì?","Cài chế độ kiểm soát, giới hạn giờ, trò chuyện với con",["Cho dùng không giới hạn","Cấm hẳn không cho học"],"Đồng hành cùng con giúp con học hiệu quả và tránh nội dung xấu.","Luật Trẻ em 2016 quy định cha mẹ có trách nhiệm bảo vệ trẻ em trên môi trường mạng.")],
 g4:[
  QZ("Shop trên mạng xã hội bán rẻ bất thường, đòi chuyển khoản 100% trước. Làm gì?","Cảnh giác; mua trên sàn uy tín hoặc trả tiền khi nhận hàng",["Chuyển ngay kẻo hết","Chuyển thêm để giao nhanh"],"Giá rẻ bất thường + bắt chuyển tiền trước là dấu hiệu lừa đảo bán hàng online.","Công an thường xuyên cảnh báo thủ đoạn lập trang bán hàng giả trên mạng xã hội, nhận tiền cọc rồi chặn liên lạc."),
  QZ("Mua hàng online bị giao sai, mình có quyền gì?","Khiếu nại, yêu cầu đổi trả theo luật",["Không có quyền gì","Chỉ mua ở chợ mới được khiếu nại"],"Mua online cũng được bảo vệ như mua ở cửa hàng.","Luật Bảo vệ quyền lợi người tiêu dùng 2023 (hiệu lực 1/7/2024) quy định người tiêu dùng có quyền được cung cấp thông tin chính xác về hàng hóa, được khiếu nại, yêu cầu đổi trả, bồi thường khi hàng hóa không đúng như đã giao kết."),
  QZ("Từ ngày 1/1/2026, hộ kinh doanh (kể cả bán hàng online) nộp thuế theo cách nào?","Bỏ thuế khoán, tự kê khai và nộp thuế theo doanh thu thực tế",["Vẫn nộp thuế khoán như cũ","Không phải nộp thuế nữa"],"Hộ kinh doanh dùng hóa đơn điện tử, phần mềm, ứng dụng để kê khai minh bạch, nộp thuế trực tuyến.","Quyết định 3389/QĐ-BTC năm 2025 của Bộ Tài chính phê duyệt Đề án chuyển đổi mô hình và phương pháp quản lý thuế đối với hộ kinh doanh khi xóa bỏ thuế khoán từ ngày 01/01/2026.")],
 st:[
  QZ("Chủ đề Ngày Chuyển đổi số quốc gia năm 2026 nhấn mạnh điều gì?","Từ kiến trúc, nền tảng, dữ liệu đến kết quả thực chất",["Số hóa mọi lúc mọi nơi","Chuyển đổi số vì phường xanh"],"Năm nay chuyển đổi số phải ra kết quả cụ thể, người dân thấy được lợi ích.","Chủ đề năm 2026: \"Chuyển đổi số quốc gia: Từ kiến trúc, nền tảng, dữ liệu đến kết quả thực chất, nâng cao hiệu quả quản trị quốc gia\"."),
  QZ("Luật An ninh mạng 2025 có hiệu lực từ ngày nào?","Ngày 1/7/2026",["Ngày 10/10/2026","Ngày 1/1/2025"],"Luật mới quy định rõ hơn việc bảo vệ người dân trên không gian mạng, nghiêm cấm phát tán tin giả, lừa đảo trên mạng.","Điều 44 Luật An ninh mạng 2025: Luật có hiệu lực thi hành từ ngày 01 tháng 7 năm 2026."),
  QZ("Luật Bảo vệ dữ liệu cá nhân có hiệu lực từ ngày nào?","Ngày 1/1/2026",["Ngày 10/10/2026","Chưa có luật này"],"Từ nay dữ liệu cá nhân của mỗi người được một đạo luật riêng bảo vệ; ai thu thập, dùng dữ liệu của mình phải theo đúng quy định.","Luật Bảo vệ dữ liệu cá nhân (Luật số 91/2025/QH15) có hiệu lực thi hành từ ngày 01 tháng 01 năm 2026.")]
};

/* ===== SỰ KIỆN NGẪU NHIÊN (6 dạng) ===== */
const EVTS={
 stranger:[
  {who:"Người lạ",line:"Chào bạn! Mình là nhân viên ngân hàng, đang tặng quà tri ân. Cho mình chụp 2 mặt thẻ căn cước nha!",q:"Bạn xử lý thế nào?",a:"Từ chối, không đưa ảnh hay thông tin căn cước cho người lạ",w:["Đồng ý, được quà mà","Chỉ cho chụp mặt trước"],ex:"Hình ảnh thẻ căn cước là dữ liệu cá nhân nhạy cảm (Điều 4 Nghị định 356/2025/NĐ-CP). Kẻ gian có thể dùng để mở tài khoản, vay tiền đứng tên bạn."},
  {who:"Người phát tờ rơi",line:"Quét mã QR này nhận Wi-Fi miễn phí và phiếu quà 500 nghìn nè!\n(Mã dẫn tới trang đòi đăng nhập ngân hàng)",q:"Bạn làm gì?",a:"Không quét, không đăng nhập; mã QR lạ có thể dẫn tới trang giả",w:["Quét và đăng nhập để nhận quà","Nhờ người nhà quét giùm"],ex:"Công an khuyến cáo không quét mã QR không rõ nguồn gốc. Trang giả sẽ đánh cắp tài khoản ngân hàng."}],
 call:[
  {who:"Số lạ 0869 *** 113",sub:"Tự xưng cán bộ Công an",line:"Anh/chị liên quan vụ án rửa tiền. Phải chuyển tiền vào tài khoản tạm giữ để chứng minh tài sản, không được nói với ai!",q:"Bạn làm gì?",a:"Cúp máy; Công an không làm việc qua điện thoại hay bắt chuyển tiền",w:["Chuyển tiền trước cho chắc","Đọc số tài khoản để họ kiểm tra"],ex:"Không có \"tài khoản tạm giữ\" nào cả. Nghi ngờ thì đến trụ sở Công an phường để xác minh."},
  {who:"Số lạ 0912 *** 567",sub:"Tự xưng nhân viên điện lực",line:"Nhà anh/chị nợ tiền điện, 2 tiếng nữa sẽ cắt điện. Bấm link trong tin nhắn để thanh toán ngay!",q:"Bạn làm gì?",a:"Không bấm link; tự kiểm tra hóa đơn qua ứng dụng hoặc tổng đài chính thức của điện lực",w:["Bấm link trả ngay kẻo bị cắt","Đọc mã OTP để họ gạch nợ"],ex:"Kẻ gian giả danh điện lực dọa cắt điện để dụ bấm link giả, chiếm tài khoản."}],
 sms:[
  {who:"Tin nhắn lạ",sms:"CHUC MUNG! So dien thoai cua ban trung thuong xe may. Nop phi 2.000.000d de nhan giai tai: ",link:"quatang-vip.com",q:"Bạn xử lý tin nhắn này thế nào?",a:"Bỏ qua, xóa tin; trúng thưởng mà đòi nộp phí trước là lừa đảo",w:["Nộp phí ngay kẻo hết hạn","Bấm link xem thử cho biết"],ex:"Giải thưởng thật không bắt nộp phí trước. Có thể phản ánh qua tổng đài 1022 của Thành phố."},
  {who:"NganHang-CSKH",sms:"[Thong bao] Tai khoan cua quy khach chua cap nhat sinh trac hoc se bi khoa trong 24h. Cap nhat tai: ",link:"nganhang-sinhtrachoc.com",q:"Bạn làm gì?",a:"Không bấm link; chỉ cập nhật trong ứng dụng ngân hàng chính thức hoặc tại quầy",w:["Bấm link cập nhật ngay","Gửi ảnh căn cước qua tin nhắn"],ex:"Việc đối chiếu sinh trắc học theo Thông tư 17/2024/TT-NHNN chỉ làm trong ứng dụng ngân hàng hoặc tại quầy. Ngân hàng không gửi link."}],
 zalo:[
  {who:"Bạn cũ",msgs:["Ê, lâu quá không gặp!","Mình đang kẹt chút việc, cho mượn 5 triệu nha, mai trả liền","Chuyển vào số tài khoản này giùm, tên chủ tài khoản khác tên mình nhưng không sao đâu"],q:"Bạn làm gì?",a:"Gọi điện trực tiếp cho bạn để xác minh, không chuyển vội",w:["Chuyển ngay vì là bạn cũ","Chuyển một nửa trước"],ex:"Tài khoản Zalo, Facebook có thể bị chiếm để lừa người quen. Luôn gọi điện xác minh, nhất là khi tên người nhận khác."},
  {who:"Nhóm \"Việc nhẹ lương cao\"",msgs:["Tuyển cộng tác viên làm tại nhà, mỗi ngày 500 nghìn – 1 triệu","Chỉ cần thả tim sản phẩm, làm nhiệm vụ","Nạp 500 nghìn để nhận nhiệm vụ đầu tiên, hoàn tiền kèm hoa hồng 30%!"],q:"Bạn làm gì?",a:"Rời nhóm, không nạp tiền làm \"nhiệm vụ\"",w:["Nạp thử 500 nghìn xem sao","Rủ thêm người quen vào nhóm"],ex:"Chiêu \"làm nhiệm vụ\" cho rút tiền lúc đầu để tạo lòng tin, sau đó bắt nạp số tiền lớn rồi chiếm đoạt."}],
 video:[
  {who:"Người thân",sub:"Cuộc gọi video",line:"Con đang cấp cứu, chuyển gấp 20 triệu vào tài khoản bạn con nhé, đừng nói ai!",q:"Hình giật, môi lệch tiếng, cuộc gọi tắt rất nhanh. Bạn làm gì?",a:"Không chuyển; gọi lại vào số quen của người thân để xác minh",w:["Chuyển ngay vì thấy đúng mặt","Chuyển một nửa trước"],ex:"Kẻ gian dùng trí tuệ nhân tạo tạo hình ảnh, giọng nói giả (deepfake). Phát hiện cũng có thể trình báo Công an phường."}],
 notify:[
  {app:"Email",who:"thongbao@dichvucong-gov.vn.com",title:"Hồ sơ của bạn bị trả lại",body:"Hồ sơ trực tuyến bị từ chối. Đăng nhập lại tại đường link để bổ sung trong 24 giờ, quá hạn sẽ bị phạt.",q:"Email này có gì đáng ngờ? Bạn làm gì?",a:"Tên miền giả; tự kiểm tra trên Cổng Dịch vụ công chính thức",w:["Bấm link đăng nhập ngay","Trả lời email gửi mật khẩu VNeID"],ex:"Tên miền có chữ \"gov.vn\" nhưng đuôi lại là \".com\". Trang cơ quan nhà nước có đuôi .gov.vn."},
  {app:"Thông báo",who:"Shop Online",title:"Đơn hàng bị thu hồi – hoàn tiền gấp đôi",body:"Sản phẩm bạn mua bị lỗi. Kết bạn Zalo nhân viên và làm theo hướng dẫn để nhận hoàn tiền.",q:"Bạn làm gì?",a:"Không làm theo; kiểm tra trực tiếp trên ứng dụng mua sắm đã dùng",w:["Kết bạn Zalo để nhận tiền","Gửi số tài khoản và mã OTP"],ex:"Kẻ gian nắm thông tin đơn hàng để tạo lòng tin rồi dụ vào link giả. Mọi hoàn tiền phải kiểm tra trên ứng dụng chính thức."}]
};
